### ISSUE TITLE
Nested block removal not working

### ISSUE THREAD

**Issue by Slinred** [Slinred/ansible-keepalived-config#1]
# Description
Trying to delete a nested `KeepAlivedConfigBlock` via state = `absent` from an ansible-playbook does not work

# Input
## Configuration
```
vrrp_instance VI_2 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass my_secret_pass
    }
    virtual_ipaddress {
        2a02:8109:2501:d400:55bb:3aef:8e45:f922/64
    }

    notify /mnt/cephfs/scripts/keepalived/keepalived_notify.sh
}
```

## playbook task
```
- name: Remove authentication from vrrp instance VI_2
  ansible_keepalived_config:
    key: "vrrp_instance VI_2.authentication"
    state: absent
```

# Expected result
The comnplete authentication block should be removed from the config and the module should report back a `changed=true`result on the first execution. The resulting config should look like this:

## Configuration
```
vrrp_instance VI_2 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    virtual_ipaddress {
        2a02:8109:2501:d400:55bb:3aef:8e45:f922/64
    }

    notify /mnt/cephfs/scripts/keepalived/keepalived_notify.sh
}
```

# Result
The module reported `changed=false` and the configuration was not changed at all.
